### ISSUE TITLE
C API doesn't delete streamers

### ISSUE THREAD

**Issue by aholtzma** [EttusResearch/uhd#145] opened 2017-11-28 23:12 UTC
I noticed that calling uhd_tx/rx_streamer_free() doesn't free the C++ streamer objects. The C container object gets deleted, but the C++ object in the rx_streamer vector does not. I get an exception when I try to get the streamer the second time:

RuntimeError: On node 0/DDC_0, output port 0 is already connected.

I attempted to call erase() on this entry w/o success:

```
uhd_error uhd_rx_streamer_free(uhd_rx_streamer_handle* h){
     UHD_SAFE_C(
         boost::mutex::scoped_lock lock(_rx_streamer_free_mutex);
-        delete (*h);
-        (*h) = NULL;
+       std::vector< uhd::rx_streamer::sptr > vec = get_usrp_ptrs()[(*h)->usrp_index].rx_streamers;
+       vec.erase(vec.begin() + (*h)->streamer_index);
+       delete *h;
+       *h = NULL;
     )
 }
```

Any ideas why this doesn't work?

**Comment by michael-west** [comment] 2018-02-10 02:00
Thank you for bringing this to our attention.  We have raised the issue to our internal issue tracker so it will be addressed.  We are closing it here, but it will remains open internally until it is resolved.

The root cause of the issue:
When the streamer is created, it is put in a vector of streamers in the usrp_ptr data structure.  Even after deleting the uhd_rx_streamer object, the streamer remains behind in the vector.  This is not the correct behavior.  The streamer should be a member of the uhd_rx_streamer data structure so it gets freed when the uhd_rx_streamer object is deleted.

**Closed by michael-west** 2018-02-10 02:00 UTC
