### ISSUE TITLE
Timed frequency switching on multiple channels not possible

### ISSUE THREAD

**Issue by Jacky2k** [EttusResearch/uhd#271] opened 2019-04-23 08:45 UTC
When switching the frequency using timed commands in a multi-channel system (X310, TwinRX) on a single timestamp for all channels, it fails without giving an error. When putting small delays between each set_command_time() before each set_rx_freq() it works just fine.
The effect of this is very strange. The received waveform is more or less correct, but the spectrum is swapped (so I guess I and Q are swapped) for every second channel. I attached a small example program to show this effect. You can set the define USE_PAUSE to 1 to enable a delay of 1 ms between the set_rx_freq() which will make the program work as expected.
The attached images show the first and the second measurement. Also after setting the frequency a second time, everything works as expected.
Edit: If it is not supported to run multiple commands at the same time (which as far as I understand should be as the documentation says somewhere that a "late command" will be executed as soon as possible) I should at least get some error message.

To compile the program you need to install some libs first:
sudo apt install libgnuplot-iostream-dev libarmadillo-dev
The program can be compiled with:
g++ -std=c++14 main.cpp -luhd -lboost_system -larmadillo -lboost_iostreams -lboost_filesystem -o main
I use an USRP X310 with two TwinRX, each fed with the same (using a -24dB power splitter) 100 MHz signal at -40 dBm (so -64 dBm at each receiver input). The USRP is connected over 10G ethernet.
UHD is "linux; GNU C++ version 5.5.0 20171010; Boost_105800; UHD_3.15.0.git-89-gf93c5227" from yesterday. FPGA image is also from yesterday using the download script - where can I find the version number? I am running an up-to-date Ubuntu 16.04.

[main.cpp.zip](https://github.com/EttusResearch/uhd/files/3106645/main.cpp.zip)
![Meas0](https://user-images.githubusercontent.com/523265/56567243-c11e0700-65b4-11e9-9774-62ccfa4eb5cd.png)
![Meas1](https://user-images.githubusercontent.com/523265/56567244-c1b69d80-65b4-11e9-9427-1320ebcc7561.png)

**Comment by Jacky2k** [comment] 2019-04-26 09:24
We just found out that even switching the frequency one after another does not fully get rid of the problem. Currently we see a random 180° phase shift of every second channel, but only for certain gain values of the USRP. This is very strange, I know, and probably cannot be reproduced by anyone without significant effort, but maybe it may help to figure out what is going on.

**Comment by michael-west** [comment] 2019-07-16 22:19
@Jacky2k The 3.14.1.0 release includes a few fixes for TwinRX, including one related to timed commands.  Please try that version and let us know if the problem is resolved.

**Comment by natetemple** [comment] 2019-07-26 01:47
@Jacky2k We have reproduced this on 3.14.1.0. We have an issue on our internal bug tracker so I'm going to close this issue. We hope to have a fix for this on an upcoming UHD release.

**Closed by natetemple** 2019-07-26 01:47 UTC
