### ISSUE TITLE
Transmitting Samples errors

### ISSUE THREAD

**Issue by karanjarich** [EttusResearch/uhd#192] opened 2018-06-25 08:29 UTC
i have installed uhd drivers well and am currently testing usrp n210 the problem is that when i try run this test   _### tx_samples_from_file --freq 915e6 --rate 5e6 --gain 10 usrp_samples.dat_ on the cmd am getting this output

C:\Program Files\UHD\lib\uhd\examples>tx_samples_from_file --freq 915e6 --rate 5e6 --gain 10 usrp_samples.dat
Win32; Microsoft Visual C++ version 14.0; Boost_106000; UHD_003.010.001.001-0-unknown

Creating the usrp device with: ...
-- Opening a USRP2/N-Series device...
-- Current recv frame size: 1472 bytes
-- Current send frame size: 1472 bytes
-- Creating WSA UDP transport for 192.168.10.2:49156
-- Creating WSA UDP transport for 192.168.10.2:49158
-- Creating WSA UDP transport for 192.168.10.2:49157
-- Creating WSA UDP transport for 192.168.10.2:49159
Error: LookupError: IndexError: multi_usrp::mb_root(18446744073709551615) - invalid vector<T> subscript

the issue at hand is that i can verify the whether it is an error or its just a setting

**Comment by michael-west** [comment] 2018-07-17 23:54
@karanjarich This may be an old issue on UHD 3.10.1.1 that has since been resolved.  Please try updating UHD to the head of the master branch or the latest UHD release (currently 3.12.0.0) and see if the issue persists.

**Comment by karanjarich** [comment] 2018-07-18 05:12
my current version is 3.12.0.0

**Comment by michael-west** [comment] 2018-07-18 08:49
@karanjarich Thank you.  We will look into it.

**Comment by karanjarich** [comment] 2018-07-18 08:57
welcome Michael could this be the reason as to why my simulated GPS signals
are weak

**Comment by mbr0wn** [comment] 2019-05-22 20:53
@karanjarich No, this is a very binary failure mode. If your device is not found, it won't work at all.

We can't reproduce this, so I'll close this unless you can provide more info to reproduce it. Thanks!

**Closed by mbr0wn** 2019-05-22 20:53 UTC
