### ISSUE TITLE
FPGA build fails under Cygwin (no such variable)

### ISSUE THREAD

**Issue by feyzaozdemir** [EttusResearch/uhd#738] opened 2024-03-28 12:34 UTC
## Issue Description ##
I followed https://files.ettus.com/manual/md_usrp3_build_instructions.html . More than 7 hours have passed after running make X410_X1_100 GUI=1 command in cygwin. I know some builds take a long time but Is it taking this long? Is this normal? What must I do?

## Setup Details ##
My OS is Windows 10, I installed Vivado 2021.1 and added patch AR76780 as in manual. I installed Cygwin and packages. Then I followed the build instructions from cygwin.

## Expected Behavior ##
Reaching the FPGA project in usrpx410 at the end of the build. If the build duration is normal, can I also get information about the accuracy of the method? If I cant reach the project after building, then how can i get the project?

## Actual Behavior ##
BUILDER: Releasing IP location: /cygdrive/e/v21_projects/uhd-master/fpga/usrp3/top/x400/build-ip/xczu28drffvg
IP build for X410_IP DONE . . .
make[1]: Leaving directory '/cygdrive/e/v21_projects/uhd-master/fpga/usrp3/top/x400'
mkdir -p ./build
tools/parse_versions_for_dts.py \
        --input regmap/x410/versioning_regs_regmap_utils.vh \
        --output dts/x410-version-info.dtsi \
        --components fpga,cpld_ifc,db_gpio_ifc,rf_core_100m,rf_core_400m
cc -o build/usrp_x410_fpga_X1_100.dts -C -E -I dts -nostdinc -undef -x assembler-with-cpp -D__DTS__ \
        $(python3 tools/get_dts_input.py --target build/usrp_x410_fpga_X1_100.dts)
make -f Makefile.x4xx.inc bin NAME=X410_X1_100 ARCH=zynquplusRFSOC PART_ID=xczu28dr/ffvg1517/-1/e  BUILD_SEED       RF_BW=100  RF_CORE_100M=1 DRAM_BANKS=1 DRAM_CH=4*1 DRAM_W=64 X410=1" DEFAULT_RFNOC_IMAGE_CORE_FILE=x41
make[1]: Entering directory '/cygdrive/e/v21_projects/uhd-master/fpga/usrp3/top/x400'
BUILDER: Checking tools...
* GNU bash, version 5.2.21(1)-release (x86_64-pc-cygwin)
* Python 3.7.12
* Vivado v2021.1_AR76780 (64-bit)
Printing MB_XDC:: constraints/timing/x410_clocks.xdc constraints/pins/common.xdc constraints/timing/shared_constraints/timing/x410.xdc constraints/timing/qsfp_10gbe.xdc constraints/pins/qsfp0_0.xdc
Printing EXTRA_DEFS:: BUILD_SEED=0 QSFP0_0=2                   RF_BW=100  RF_CORE_100M=1 DRAM_BANKS=1 DRAM_CH
Using parser configuration from: /cygdrive/e/v21_projects/uhd-master/fpga/usrp3/top/x400/dev_config.json
[00:00:00] Executing command: vivado -mode gui -source E:/v21_projects/uhd-master/fpga/usrp3/top/x400/build_x
[07:16:53] Current task: Initialization +++ Current Phase: Starting

**Comment by wordimont** [comment] 2024-03-28 13:33
You requested the GUI. Did the Vivado GUI open? If you build it in the GUI then the GUI will stay open until you close it and you won't really get any information in the terminal. Perhaps the GUI is waiting for you. If the GUI isn't opening, you could try building it without the GUI=1 option.

Build time depends on your computer, if it has to build the IP or not, and which USRP target. I would guess an hour to build that particular target if you already built the IP.

**Comment by wordimont** [comment] 2024-03-28 14:26
Make sure the Tcl console was open in the GUI and see if there was any output. You can also check the `build` and `build-X410_X1_100` directories to see if any files were produced. If not, then I would guess this problem is related to running under Cygwin. See if it works without the GUI=1 option. You should see lots of output to the terminal if it's working.

Building in the GUI and in the terminal should be the same. It's just running Vivado either way. People use the GUI option if they want to use the GUI at the end of the build while the design is still in memory. But you can basically do the same thing by loading the final checkpoint in Vivado after the build is done in the terminal.

**Comment by wordimont** [comment] 2024-03-29 11:58
Can you open `build-X410_X1_100/build.log` and see if there's an error message or warning in there?

Which UHD version branch/commit are you building from?

**Comment by wordimont** [comment] 2024-03-29 12:41
Try building off of the latest release branch (`UHD-4.6`). I don't recommend building off of master unless you have a specific reason. I'll have to reproduce this on Cygwin to see what's going on. It looks like some variables aren't being defined.

**Comment by wordimont** [comment] 2024-04-01 13:02
USRP builds use Vivado's non-project mode. For a quick summary see the FAQ here:
https://kb.ettus.com/RFNoC_Frequently_Asked_Questions#How_do_I_create_a_Vivado_project_for_my_FPGA_build.3F

**Comment by wordimont** [comment] 2024-04-01 15:50
I found the cause of the original issue on master and created a pull request with a fix. There was a variable (VIV_SAVE) set to an empty string, which works fine under Linux but for some reason it doesn't work under Cygwin/Windows. Turns out it was empty because we were pulling the value from the wrong variable.

**Closed as completed** 2024-04-02 13:26 UTC
