### ISSUE TITLE
uhd::transport::sph::send_packet_streamer_send() lead to Segmentation fault

### ISSUE THREAD

**Issue by liuzhikui** [EttusResearch/uhd#144] opened 2017-11-28 02:39 UTC
When I run USRP B210,after some time,**uhd::transport::sph::send_packet_streamer_send()** triggered **Segmentation fault**
Here is the backtrace:
![2017-11-28 10_11_59 _______________](https://user-images.githubusercontent.com/28185487/33299653-90bb434a-d427-11e7-808c-3b40ae90e074.png)

**Comment by michael-west** [comment] 2018-02-10 02:17
A segmentation fault of this type can be (and usually is) caused by invalid parameters to the uhd_tx_streamer_send() call.  There can be other causes, but we are unable to reproduce the issue without more detail.

Closing this issue for now.  If you want to re-open it, please provide detail on how to reproduce the error.

**Closed by michael-west** 2018-02-10 02:17 UTC

**Comment by michael-west** [comment] 2018-04-26 17:10
Root cause identified in #171.
