### ISSUE TITLE
dissectors wireshark API changes

### ISSUE THREAD

**Issue by selinux** [EttusResearch/uhd#88] opened 2017-02-01 22:14 UTC
when I start wireshark 2.2.3 after succesfully build wireshark dissectors I get an...
chdr-plugin.so: undefined symbol tvb_get_string

It seems that tvb_get_string() has been replaced by tvb_get_string_enc() 

from wireshark...

=== Major API Changes
* tvb_get_string and tvb_get_stringz have been replaced with
tvb_get_string_enc and tvb_get_stringz_enc respectively.

**Comment by mbr0wn** [comment] 2017-02-02 13:28
@selinux Thanks for the pointer! We'll need to make sure we support a spectrum of Wireshark APIs, but this seems fixable.

**Comment by mbr0wn** [comment] 2017-06-21 19:57
I remember seeing this, too, but I can't reproduce now. I have the dissector running on 2.2.6. Not sure if some changes were required, but I'm closing unless we find a way to reproduce this.

**Closed by mbr0wn** 2017-06-21 19:57 UTC
