### ISSUE TITLE
Cordic DSP frequency tuning saturated to sample rate (not master clock rate) in X310+UBX in UHD-4.1

### ISSUE THREAD

**Issue by adriengit** [EttusResearch/uhd#474] opened 2021-08-06 14:10 UTC
## Issue Description ##
The cordic DSP frequency tuning saturated to sample rate (not master clock rate) in X310+UBX in UHD-4.1.
So, DSP frequency suffers reduced range.

## Setup Details ##
UHD : version: 4.1.0.1-0-gf633b497 (the issue is not present with UHD 3.15)
OS: Ubuntu 20.04
Hardware : X310+UBX160 2944R (or B210)

## Expected Behavior ##
Having a master clock rate of 200MSps on X310, manually tuning the dsp frequency at +50MHz should result in a frequency offset of 50MHz. This works fine in UHD 3.15.

## Actual Behaviour ##
Instead, the actual frequency is limited to the LO frequency plus half the sample rate.

## Steps to reproduce the problem ##
One could copy the tx_burst.cpp examples and add tune frequency in the MANUAL mode.

```cpp
//
// Copyright 2010-2011,2014 Ettus Research LLC
// Copyright 2018,2019 Ettus Research, a National Instruments Company
//
// SPDX-License-Identifier: GPL-3.0-or-later
//

#include <uhd/usrp/multi_usrp.hpp>
#include <uhd/utils/safe_main.hpp>
#include <uhd/utils/thread.hpp>
#include <boost/algorithm/string.hpp>
#include <boost/format.hpp>
#include <boost/program_options.hpp>
#include <boost/thread/thread.hpp>
#include <complex>
#include <csignal>
#include <iostream>
#include <vector>

namespace po = boost::program_options;

static bool stop_signal_called = false;
void sig_int_handler(int)
{
    stop_signal_called = true;
}

int UHD_SAFE_MAIN(int argc, char* argv[])
{
    // variables to be set by po
    std::string args, channel_list, subdev, ref;
    double seconds_in_future, rate, freq, rep_rate, gain, lo_offset, bw;
    size_t total_num_samps;
    float ampl;

    // setup the program options
    po::options_description desc("Allowed options");
    // clang-format off
    desc.add_options()
        ("help", "help message")
        ("args", po::value<std::string>(&args)->default_value(""), "multi uhd device address args")
        ("secs", po::value<double>(&seconds_in_future)->default_value(1.5), "delay before first burst")
        ("repeat", "repeat burst")
        ("rep-delay", po::value<double>(&rep_rate)->default_value(0.5), "delay between bursts")
        ("nsamps", po::value<size_t>(&total_num_samps)->default_value(10000), "total number of samples to transmit")
        ("rate", po::value<double>(&rate)->default_value(100e6/16), "rate of outgoing samples")
        ("ampl", po::value<float>(&ampl)->default_value(float(0.3)), "amplitude of each sample")
        ("freq", po::value<double>(&freq)->default_value(0), "center frequency")
        ("gain", po::value<double>(&gain)->default_value(0), "gain")
        ("dilv", "specify to disable inner-loop verbose")
        ("channels", po::value<std::string>(&channel_list)->default_value("0"), "which channel(s) to use (specify \"0\", \"1\", \"0,1\", etc")
        ("int-n", "tune USRP with integer-n tuning")
        ("subdev", po::value<std::string>(&subdev), "subdevice specification")
        ("ref", po::value<std::string>(&ref)->default_value("internal"), "reference source (internal, external, mimo)")
        ("lo-offset", po::value<double>(&lo_offset)->default_value(0.0),
            "Offset for frontend LO in Hz (optional)")
        ("bw", po::value<double>(&bw), "analog frontend filter bandwidth in Hz")
    ;
    // freq list
    std::vector<float> lo_offsets;
    float deltaF = 1e6;
    int nb_freq = 100;
    int idx_offset = 0;
    for(int i=0; i<nb_freq; i++)
        lo_offsets.push_back(deltaF * i);

    // clang-format on
    po::variables_map vm;
    po::store(po::parse_command_line(argc, argv, desc), vm);
    po::notify(vm);

    // print the help message
    if (vm.count("help")) {
        std::cout << boost::format("UHD TX Timed Samples %s") % desc << std::endl;
        return ~0;
    }

    bool verbose = vm.count("dilv") == 0;
    bool repeat  = vm.count("repeat") != 0;

    // create a usrp device
    std::cout << std::endl;
    std::cout << boost::format("Creating the usrp device with: %s...") % args
              << std::endl;
    uhd::usrp::multi_usrp::sptr usrp = uhd::usrp::multi_usrp::make(args);

    // Lock mboard clocks
    if (vm.count("ref")) {
        usrp->set_clock_source(ref);
    }

    // always select the subdevice first, the channel mapping affects the other settings
    if (vm.count("subdev"))
        usrp->set_tx_subdev_spec(subdev);

    std::cout << boost::format("Using Device: %s") % usrp->get_pp_string() << std::endl;

    // detect which channels to use
    std::vector<std::string> channel_strings;
    std::vector<size_t> channel_nums;
    boost::split(channel_strings, channel_list, boost::is_any_of("\"',"));
    for (size_t ch = 0; ch < channel_strings.size(); ch++) {
        size_t chan = std::stoi(channel_strings[ch]);
        if (chan >= usrp->get_tx_num_channels()) {
            throw std::runtime_error("Invalid channel(s) specified.");
        } else
            channel_nums.push_back(std::stoi(channel_strings[ch]));
    }

    // set the tx sample rate
    std::cout << boost::format("Setting TX Rate: %f Msps...") % (rate / 1e6) << std::endl;
    usrp->set_tx_rate(rate);
    std::cout << boost::format("Actual TX Rate: %f Msps...") % (usrp->get_tx_rate() / 1e6)
              << std::endl
              << std::endl;

    // set the center frequency
    if (not vm.count("freq")) {
        std::cerr << "Please specify the center frequency with --freq" << std::endl;
        return ~0;
    }

    std::cout << boost::format("Setting TX Freq: %f MHz...") % (freq / 1e6) << std::endl;
    std::cout << boost::format("Setting TX LO Offset: %f MHz...") % (lo_offset / 1e6)
              << std::endl;

    for (size_t i = 0; i < channel_nums.size(); i++) {
        uhd::tune_request_t tune_request;
        tune_request = uhd::tune_request_t(freq, lo_offset);

        //tune_request.dsp_freq_policy = uhd::tune_request_t::POLICY_MANUAL;
        //tune_request.rf_freq_policy = uhd::tune_request_t::POLICY_AUTO;
        //tune_request.dsp_freq = lo_offsets[idx_offset];
        //tune_request.rf_freq = freq;

        if (vm.count("int-n"))
            tune_request.args = uhd::device_addr_t("mode_n=integer");
        usrp->set_tx_freq(tune_request, channel_nums[i]);
    }
    std::cout << boost::format("Actual TX Freq: %f MHz...") % (usrp->get_tx_freq() / 1e6)
              << std::endl
              << std::endl;

    std::cout << boost::format("Setting TX Gain: %f...") % (gain) << std::endl;
    for (size_t i = 0; i < channel_nums.size(); i++)
        usrp->set_tx_gain(gain, channel_nums[i]);
    std::cout << boost::format("Actual TX Gain: %f...") % (usrp->get_tx_gain())
              << std::endl
              << std::endl;

    // set the analog frontend filter bandwidth
    if (vm.count("bw")) {
        std::cout << boost::format("Setting TX Bandwidth: %f MHz...") % (bw / 1e6)
                  << std::endl;
        usrp->set_tx_bandwidth(bw);
        std::cout << boost::format("Actual TX Bandwidth: %f MHz...")
                         % (usrp->get_tx_bandwidth() / 1e6)
                  << std::endl
                  << std::endl;
    }

    std::cout << boost::format("Setting device timestamp to 0...") << std::endl;
    usrp->set_time_now(uhd::time_spec_t(0.0));

    // create a transmit streamer
    uhd::stream_args_t stream_args("fc32"); // complex floats
    stream_args.channels             = channel_nums;
    uhd::tx_streamer::sptr tx_stream = usrp->get_tx_stream(stream_args);

    // allocate buffer with data to send
    const size_t spb = tx_stream->get_max_num_samps();

    std::vector<std::complex<float>> buff(spb, std::complex<float>(ampl, ampl));
    std::vector<std::complex<float>*> buffs(channel_nums.size(), &buff.front());

    std::signal(SIGINT, &sig_int_handler);
    if (repeat)
        std::cout << "Press Ctrl + C to quit..." << std::endl;

    double time_to_send = seconds_in_future;

    do {
        // setup metadata for the first packet
        uhd::tx_metadata_t md;
        md.start_of_burst = true;
        md.end_of_burst   = false;
        md.has_time_spec  = true;
        md.time_spec      = uhd::time_spec_t(time_to_send);

        // the first call to send() will block this many seconds before sending:
        double timeout = std::max(rep_rate, seconds_in_future)
                         + 0.1; // timeout (delay before transmit + padding)

        size_t num_acc_samps = 0; // number of accumulated samples
        while (num_acc_samps < total_num_samps) {
            size_t samps_to_send = total_num_samps - num_acc_samps;
            if (samps_to_send > spb) {
                samps_to_send = spb;
            } else {
                md.end_of_burst = true;
            }

            // send a single packet
            size_t num_tx_samps = tx_stream->send(buffs, samps_to_send, md, timeout);
            // do not use time spec for subsequent packets
            md.has_time_spec  = false;
            md.start_of_burst = false;

            if (num_tx_samps < samps_to_send) {
                std::cerr << "Send timeout..." << std::endl;
                if (stop_signal_called) {
                    exit(EXIT_FAILURE);
                }
            }

            if (verbose) {
                std::cout << boost::format("Sent packet: %u samples") % num_tx_samps
                          << std::endl;
            }

            num_acc_samps += num_tx_samps;
        }

        time_to_send += rep_rate;

        std::cout << std::endl << "Waiting for async burst ACK... " << std::flush;
        uhd::async_metadata_t async_md;
        size_t acks = 0;
        // loop through all messages for the ACK packets (may have underflow messages in
        // queue)
        while (acks < channel_nums.size()
               and tx_stream->recv_async_msg(async_md, seconds_in_future)) {
            if (async_md.event_code == uhd::async_metadata_t::EVENT_CODE_BURST_ACK) {
                acks++;
            }
        }
        std::cout << (acks == channel_nums.size() ? "success" : "fail") << std::endl;

        // change freq

        for (size_t i = 0; i < channel_nums.size(); i++) {
            uhd::tune_request_t tune_request;
            if (idx_offset==lo_offsets.size())
                idx_offset = 0;
            //tune_request = uhd::tune_request_t(freq+lo_offsets[idx_offset], lo_offsets[idx_offset]);

            tune_request.dsp_freq_policy = uhd::tune_request_t::POLICY_MANUAL;
            tune_request.rf_freq_policy = uhd::tune_request_t::POLICY_MANUAL;
            tune_request.dsp_freq = lo_offsets[idx_offset];
            tune_request.rf_freq = freq;          
            if (vm.count("int-n"))
                tune_request.args = uhd::device_addr_t("mode_n=integer");
            usrp->set_tx_freq(tune_request, channel_nums[i]);
            idx_offset++;
        }

        std::cout << boost::format("Set TX Freq: %f MHz...") % ((freq + lo_offsets[idx_offset-1])/ 1e6)
                    << std::endl
                    << std::endl;    
        std::cout << boost::format("Actual TX Freq: %f MHz...") % (usrp->get_tx_freq() / 1e6)
                << std::endl
                << std::endl;                                

    } while (not stop_signal_called and repeat);

    // finished
    std::cout << std::endl << "Done!" << std::endl << std::endl;

    return EXIT_SUCCESS;
}
```

## Additional Information ##
From the Manual, one could read : 

page_general.html

> When using hand-crafted tune requests, it is necessary to observe sampling theory. If the LO offset of a tune request exceeds the sampling rate, the actual DSP frequency will wrap around. For example, if a B210 is used at a master clock rate of 20 MHz, and the LO frequency is set to 100 MHz, the digital tuning range is 90 MHz to 110 MHz. Now, if an LO offset of 12 MHz is selected, it will wrap and become an LO offset of -8 MHz, and the final frequency will become 92 MHz. However, if there is no anti-aliasing filter enabled, there will be an alias at 112 MHz, as requested.

I tested this with B210, but this is not the case. Using a LO offset of +12MHz will become a LO offset of +10MHz. The LO offset is saturated.

Reviewing the change log, it appears a modification to make_overall_tune_range. I tried to replace with the 3.15 function, without great effect.

* multi_usrp
  - Factor out make_overall_tune_range() and fix limits

**Comment by mbr0wn** [comment] 2021-08-24 09:59
OK this took me a bit to understand. I tried replicating this on a Python REPL, but it turns out the bug won't trigger if there's a) no streamer yet, and b) it's a TX-bug only. The root cause was then soon identified.

@adriengit thanks for the excellent bug report. I think the patch below will fix this, but it's in our internal review pipeline and will get published when we've finished reviews etc. When the patch gets merged into master, this issue will get closed, even if it's not yet public -- but that means it will be public very soon.

```patch
From 20d5a3b557b44f6e05f8bb27f56e999a136cfe2b Mon Sep 17 00:00:00 2001
From: Martin Braun <martin.braun@ettus.com>
Date: Tue, 24 Aug 2021 11:45:31 +0200
Subject: [PATCH] rfnoc: duc: Fix frequency range for DUC block

The tuning range of the DUC depends on the output sample rate (which is
larger), but it was using the input sample rate. This was causing a bug
where for Tx, the DSP tuning range was limited when using multi_usrp API,
and thus would not allow to DSP-tune beyond the current sampling rate.

In this patch, we also re-use the existing calculation of the sampling
rate, and harmonize that code between duc_block_control and
ddc_block_control.

Consider the following Python REPL code:

>>> import uhd
>>> U = uhd.usrp.MultiUSRP('type=x300')
>>> U.set_rx_rate(10e6)
>>> U.set_tx_rate(10e6)
>>> # Creating a streaming is required, or the input rate will not be
>>> # set:
>>> S = U.get_tx_stream(uhd.usrp.StreamArgs("fc32", "sc16"))
>>> treq = uhd.types.TuneRequest(1e9)
>>> treq.rf_freq = 1e9
>>> treq.dsp_freq = 50e6
>>> treq.dsp_freq_policy = uhd.types.TuneRequestPolicy.manual
>>> treq.rf_freq_policy = uhd.types.TuneRequestPolicy.manual
>>> tres = U.set_rx_freq(treq, 0)
>>> print(str(tres))
Tune Result:
Target RF  Freq: 1000.000000 (MHz)
Actual RF  Freq: 1000.000000 (MHz)
Target DSP Freq: 50.000000 (MHz)
Actual DSP Freq: 5.000000 (MHz)
>>> # Note the last two lines: The *target* DSP freq was already clipped
>>> # to 5 MHz. These lines show 50.0 MHz when this patch is applied.
---
 host/lib/rfnoc/ddc_block_control.cpp | 3 +--
 host/lib/rfnoc/duc_block_control.cpp | 5 ++---
 2 files changed, 3 insertions(+), 5 deletions(-)

diff --git a/host/lib/rfnoc/ddc_block_control.cpp b/host/lib/rfnoc/ddc_block_control.cpp
index 3326d4e46..dbcb1b763 100644
--- a/host/lib/rfnoc/ddc_block_control.cpp
+++ b/host/lib/rfnoc/ddc_block_control.cpp
@@ -126,8 +126,7 @@ public:
 
     uhd::freq_range_t get_frequency_range(const size_t chan) const override
     {
-        const double input_rate =
-            _samp_rate_in.at(chan).is_valid() ? _samp_rate_in.at(chan).get() : 1.0;
+        const double input_rate = get_input_rate(chan);
         // TODO add steps
         return uhd::freq_range_t(-input_rate / 2, input_rate / 2);
     }
diff --git a/host/lib/rfnoc/duc_block_control.cpp b/host/lib/rfnoc/duc_block_control.cpp
index 12937ac21..7b0a49410 100644
--- a/host/lib/rfnoc/duc_block_control.cpp
+++ b/host/lib/rfnoc/duc_block_control.cpp
@@ -123,10 +123,9 @@ public:
 
     uhd::freq_range_t get_frequency_range(const size_t chan) const override
     {
-        const double input_rate =
-            _samp_rate_in.at(chan).is_valid() ? _samp_rate_in.at(chan).get() : 1.0;
+        const double output_rate = get_output_rate(chan);
         // TODO add steps
-        return uhd::freq_range_t(-input_rate / 2, input_rate / 2);
+        return uhd::freq_range_t(-output_rate / 2, output_rate / 2);
     }
 
     double get_input_rate(const size_t chan) const override
-- 
2.25.1
```

**Closed** 2021-08-30 17:31 UTC

**Comment by adriengit** [comment] 2021-09-08 12:19
Thank you Martin, this solve the issue!
