### ISSUE TITLE
Incorrect Python Directory for UHD install 

### ISSUE THREAD

**Issue by dylan-baros** [EttusResearch/uhd#646] opened 2022-11-19 19:58 UTC
## Issue Description ##

Seems to be a path issue when installing UHD with Python support on Ubuntu 22.04.1. The installation directory is now incorrect. 

Short example snippet of installation logs:

Before with 20.04-> 
``` 
-- Installing: /usr/local/lib/python3.8/site-packages/usrp_mpm/sys_utils/__init__.py
-- Installing: /usr/local/lib/python3.8/site-packages/usrp_mpm/sys_utils/gpio.py 
```
After with 22.04.1->
```
-- Installing: /usr/local/local/lib/python3.10/dist-packages/usrp_mpm/sys_utils/__init__.py
-- Installing: /usr/local/local/lib/python3.10/dist-packages/usrp_mpm/sys_utils/gpio.py
```

As you can see, /local/local/ should just be /local/.

## Setup Details ##

x410 Running UHD 4.3
Ubuntu 22.04.1
Git commit: 6c647732253e5ce27f840b472fcdeb9a0ae3b648

## Expected Behavior ##

I expect the local directory to not be copied twice. 

## Actual Behaviour ##

/local/ becomes /local/local/

## Steps to reproduce the problem ##

Install UHD from commit above with Python cmake flag.

**Comment by dylan-baros** [comment] 2022-11-19 19:58
@michaelld

**Comment by michaelld** [comment] 2022-11-21 16:29
@dylan-baros what is the full `cmake` command you're executing?

**Comment by dylan-baros** [comment] 2022-11-21 16:31
> @dylan-baros what is the full `cmake` command you're executing?

cmake .. -DENABLE_PYTHON_API=ON

**Comment by LawsonGu** [comment] 2022-11-29 08:29
I have switch to python3.9 in ubuntu 22.04.1
CMake command:
```
cmake -DPYTHON_INCLUDE_DIR=/usr/include/python3.9 -DPYTHON_LIBRARY=/usr/lib/x86_64-linux-
gnu/libpython3.9.so -DENABLE_PYTHON_API=ON ..
```
Result:
![image](https://user-images.githubusercontent.com/101655210/204478082-13a39e18-2215-44d0-86a5-3e3213fcba51.png)

**Comment by jdemel** [comment] 2022-12-19 08:39
@dylan-baros #628 should describe the same issue. I'm glad I'm not the only one stumbling over this.

**Comment by mbr0wn** [comment] 2023-01-09 14:52
Dupe of #628. Closing this.

**Closed by mbr0wn** 2023-01-09 14:52 UTC
