### ISSUE TITLE
[RFNoC] rb_stb not being read back correctly during setup in testbench

### ISSUE THREAD

**Issue by bpadalino** [EttusResearch/uhd#307] opened 2019-11-05 22:55 UTC
## Issue Description ##
It seems that starting with v3.14.1.0-rc1 (e39334fec382d6bfc85b442f58289db485ea9742 of the fpga repository is the offending commit) a change in the readback strobe caused a block of mine to stop working in a testbench.  This particular block does not have any readback registers, so I had set `rb_stb` to `1'b0`.  With this setup, the simulation never gets past `Connecting noc_block_tb (SID: 1:0) to noc_block_myblock (SID: 0:0)`.

## Setup Details ##
Ubuntu 19.04
Vivado 2017.4
UHD FPGA repository at e39334fec382d6bfc85b442f58289db485ea9742

## Expected Behavior ##
My user code `rb_stb` should not have any effect on the RFNoC setup.

## Actual Behaviour ##
The RFNoC testbench stalls when trying to connect blocks.

## Steps to reproduce the problem ##
Checkout the FPGA repository at e39334fec382d6bfc85b442f58289db485ea9742 and change a testbench `rb_stb` to be `1'b0` instead of `1'b1`.  Ensure the block that is changed has no user readback registers checked during the testbench (like `noc_block_keep_one_in_n.v`).  Run `make xsim` and the problem should be seen.

**Comment by wordimont** [comment] 2021-08-31 00:10
@bpadalino I was taking a look at this issue, and I think what you observed is expected behavior. The code was changed so that the rb_stb can be used to reliably throttle writes. Driving rb_stb with 1'b0 during a write tells the noc_shell to hold off the write acknowledgement, indefinitely stalling settings bus. I appreciate that this may seem unintuitive. But I think you already figured out the correct fix, which is to have rb_stb default to 1.

Let me know if you think I've overlooked something. I will close this issue since I assume you have already implemented your fix for the problem.

**Closed by wordimont** 2021-08-31 00:10 UTC
Labels: Tracking
