### ISSUE TITLE
Pybombs mako problem

### ISSUE THREAD

**Issue by jamisxom** [EttusResearch/uhd#45] opened 2015-09-16 11:13 UTC
Hi, I've been unable to use pybombs to install UHD or anything that depends on UHD.

I'm starting fresh on a brand new installation of Ubuntu 14.04.
I've pulled the latest pybombs from git.

The issue is possibly something to do with Mako, although I've tried after installing mako using both pybombs
    ./pybombs install mako
which reports that I have mako and that the version is recent enough.
When that didn't work, I uninstalled mako using pybombs and then reinstalled it from the repositories:
    sudo apt-get install python-mako
and still have the same problem.
Pybombs has been able to install other recipies that don't seem to depend on UHD. I've found a few posts about similar problems but most seem to have been solved by installing mako, which hasn't worked for me.
Does anyone have any suggestions?

In the meantime, I've gone ahead and installed gnuradio and uhd using apt-get. Does that potentially conflict with the use of pybombs?

```
-- 
-- Python checking for Python version 2.6 or greater
-- Python checking for Python version 2.6 or greater - found
-- 
-- Python checking for Mako templates 0.4 or greater
-- Python checking for Mako templates 0.4 or greater - "import mako" failed
-- 
-- Configuring LibUHD support...
--   Dependency Boost_FOUND = 1
--   Dependency HAVE_PYTHON_PLAT_MIN_VERSION = TRUE
--   Dependency HAVE_PYTHON_MODULE_MAKO = FALSE
CMake Error at cmake/Modules/UHDComponent.cmake:51 (MESSAGE):
  Dependencies for required component LibUHD not met.
Call Stack (most recent call first):
  CMakeLists.txt:279 (LIBUHD_REGISTER_COMPONENT)
```

**Comment by mbr0wn** [comment] 2015-09-16 16:12
@jamisxom, this doesn't look like a UHD bug, rather a path setup problem. I recommend you take this to the mailing list, so we can get a conversation going to fix your problem. In the meantime, I'll be closing this issue.

**Comment by mbr0wn** [comment] 2015-09-16 16:12
When you do contact the mailing list, show us the output of

    $ python -c 'import mako'

**Comment by closehaulcom** [comment] 2015-10-02 17:07
I encountered the same issue.  I attempted to re-install python-mako with the usual sudo apt-get install, command, to no avail.  However, it magically worked after I tried Plan B:

_$ pip install mako_

**Comment by mbr0wn** [comment] 2018-06-22 21:28
It should yes. Which Ubuntu? Which Pybombs?

**Comment by ndandanov** [comment] 2018-06-23 22:02
I just encountered the same issue on a fresh Ubuntu 18.04 x64 install while trying to install `gnuradio` using the [official PyBOMBS recipe](https://github.com/gnuradio/pybombs).
`pip install mako` and `sudo apt-get install python-mako` seems to have resolved it. I will report later if any other issues occur.

**Comment by mbr0wn** [comment] 2018-06-25 18:28
@ndandanov Which PyBOMBS version did you use? Did you install via pip `$ pip install pybombs` or from source?

**Comment by ndandanov** [comment] 2018-06-26 08:05
@mbr0wn I installed it via `pip`. Then I read that this issue has been fixed and installed from source.

**Comment by mbr0wn** [comment] 2018-06-26 15:54
Did that fix it?

**Comment by ndandanov** [comment] 2018-06-26 20:07
Sorry, I think I switched to the latest source for another bug which popped up later during the installation.
I can try to replicate the issue in a fresh Ubuntu install however :) That would be no problem for me.

**Comment by mbr0wn** [comment] 2018-06-28 00:29
No that's fine! It seems to work with the latest pip though.

**Comment by hz5612777** [comment] 2019-06-05 03:18
I have encountered the same problem, even if **mako** is properly installed, it is still useless.  I found it is a version issue. UHD called the python3 version, so pip should correspond to python3.  When I use **pip3 install mako**, the problem is solved.

**Comment by jarvisAUT** [comment] 2019-08-21 14:25
> 
> 
> I have encountered the same problem, even if **mako** is properly installed, it is still useless. I found it is a version issue. UHD called the python3 version, so pip should correspond to python3. When I use **pip3 install mako**, the problem is solved.

Solved it for me.

**Comment by cbdonohue** [comment] 2019-09-04 01:32
Should Pybombs be updated to avoid this?

**Comment by mbr0wn** [comment] 2019-09-22 20:56
PyBOMBS has been updated on master branch to do this.

**Closed by mbr0wn** 2019-09-22 20:57 UTC

**Comment by ahmad-sho** [comment] 2021-12-10 08:47
Hi, I had a simmilar problem trying to install gnuradio: I have the following messages:
...
-- Python checking for mako >= 0.4.2
-- Python checking for mako >= 0.4.2 - not found
-- 
-- Python checking for six - python 2 and 3 compatibility library
-- Python checking for six - python 2 and 3 compatibility library - not found


I tried to install mako after seeing the suggestions above, but I already have a new version:
Requirement already satisfied: mako in /usr/lib/python3/dist-packages (1.1.0)
any suggestions?
I'm running Ubuntu 20.04.3 with python3 installed.

**Comment by ahmad-sho** [comment] 2021-12-10 08:49
Hi, I had a similar problem trying to install gnuradio: I have the following messages:

-- Python checking for mako >= 0.4.2
-- Python checking for mako >= 0.4.2 - not found
-- Python checking for six - python 2 and 3 compatibility library
-- Python checking for six - python 2 and 3 compatibility library - not found

I tried to install mako after seeing the suggestions above, but I already have a new version:
Requirement already satisfied: mako in /usr/lib/python3/dist-packages (1.1.0)
any suggestions?
I'm running Ubuntu 20.04.3 with python3 installed.
