### ISSUE TITLE
Could not create nirio_zero_copy transport error

### ISSUE THREAD

**Issue by mdmikh** [EttusResearch/uhd#138] opened 2017-11-01 12:12 UTC
There is a problem related to reusing rx/tx streams for X310 device connected through PCIe. Below is a test program that demonstrates the issue.  The output is the following:

```
$ sudo ./test1
linux; GNU C++ version 4.8.4; Boost_105400; UHD_003.010.002.000-5-g4bbf0c20

Found type=x300,resource=RIO0,product=X310,fpga=HG...
-- X300 initialization sequence...
-- Connecting to niusrpriorpc at localhost:5444...
...
terminate called after throwing an instance of 'uhd::runtime_error'
  what():  RuntimeError: Could not create nirio_zero_copy transport. A parameter to a function was not valid. This could be a NULL pointer, a bad value, etc. (Error code -52005)
```

The program calls get_rx_stream several times just to query maximum number of samples. It is expected that corresponding streamer object and related HW/SW resources are disposed every time as only temporary object is created. But subsequent get_tx_stream call ends with runtime error what indicates possible resources leak.

```
#include <iostream> 
#include <fstream> 
#include <csignal> 
#include <complex>
#include <uhd/usrp/multi_usrp.hpp> 

using namespace std;

/*
 * 
 */
int main(int argc, char** argv) {
    
    std::string args;
    uhd::device_addrs_t device_adds = uhd::device::find(args);

    if(device_adds.size() == 0) {
        std::cerr<<"No USRP Device Found. " << std::endl;
        return -1;
    } else {
        args = device_adds.at(0).to_string() ;
        std::cout << "Found " << args << std::endl;
    }
    
    uhd::usrp::multi_usrp::sptr usrp = uhd::usrp::multi_usrp::make(args);
    uhd::stream_args_t stream_args("sc16", "sc16");

    usrp->get_rx_stream(stream_args)->get_max_num_samps();
    usrp->get_rx_stream(stream_args)->get_max_num_samps();
    usrp->get_rx_stream(stream_args)->get_max_num_samps();
    usrp->get_tx_stream(stream_args)->get_max_num_samps();
    return 0;
}
```

**Comment by michael-west** [comment] 2018-03-27 18:03
Thank you for the detailed description and code sample.

This is a known issue on the X300/X310 and we are working to fix it.  The issue is being tracked on our internal issue tracker and will be addressed.  We are closing it here to avoid tracking it in 2 places.

**Closed by michael-west** 2018-03-27 18:03 UTC
Labels: bug
