### ISSUE TITLE
UHD failure due to libboost_filesystem.so.1.73.0 : No such file or directory

### ISSUE THREAD

**Issue by AmineBenz** [EttusResearch/uhd#784] opened 2024-09-04 15:32 UTC
## Issue Description ##

I tried to install UDH from a tutorial, but I get this error when executing any UDH command (for example udh_find_devices): 

> uhd_adc_self_cal: error while loading shared libraries: libboost_filesystem.so.1.73.0: cannot open shared object file: No such file or directory

I tried different boost versions, including the 1.73.0, but nothing works, it's still the same output.

## Additional Information ##

Here is the tutorial in question : 
https://kb.ettus.com/Building_and_Installing_the_USRP_Open-Source_Toolchain_(UHD_and_GNU_Radio)_on_Linux

**Comment by mbr0wn** [comment] 2024-09-30 12:53
I'm closing this (see our conversation in the other issue) as it seems to be a support question, not a bug.

**Closed by mbr0wn** 2024-09-30 12:53 UTC
