### ISSUE TITLE
Ettus site is not available in CIS

### ISSUE THREAD

**Issue by medvedvvs** [EttusResearch/uhd#383] opened 2020-09-22 12:02 UTC
## Issue Description ##

Site ettus.com is not available in CIS (RU, KZ, BY...) for 2 months.

**Comment by michaelld** [comment] 2020-09-22 12:30
There are countries that Ettus is prohibited from providing service to by the US Government. Some countries were added to the list recently; could be those specific countries, and maybe more. The US Government sets the list of these counties; Ettus just follows their requirements -- it is US law to do so, and thus Ettus would be in violation of the law if Ettus didn't follow the requirements. The issue is outside the scope of our jurisdiction; hence, I'm closing this ticket. Maybe someone with these issues in the future will see this message and get a better idea of what might be going on.

**Closed by michaelld** 2020-09-22 12:30 UTC
