### ISSUE TITLE
X310 Build Issue

### ISSUE THREAD

**Issue by arash1366j** [EttusResearch/uhd#387] opened 2020-10-06 09:02 UTC
Dear All,

I followed the build instruction for generation 3 on the website.
All requirement and dependencies are fulfilled as well as Xilinx Vivado 2019.1.
I would like to save the project in Vivado for future customization, therefore I ran "make X310_HG GUI=1".
The makefile launch Vivado successfully, after configuration is done when I save the project using save as option in the Vivado. as I press generate bitstream in the Vivado, It automatically starts from synthesis phase, and it gives me the following errors in the synthesis phase:
My UHD version is currently 3.14 LTS, I tried the FPGA source from different branches (e.g uhd3.14 LTS and uhd3.15 LTS) always results in the same errors.

[Synth 8-1766] cannot open include file ../../lib/io_port2/LvFpga_Chinch_Interface.vh ["/home/scoe-adm/Downloads/uhd-master/fpga/usrp3/top/x300/build-X310_HG/X310.srcs/sources_1/imports/usrp3/top/x300/x300.v":18]

[Synth 8-2715] syntax error near ; ["/home/scoe-adm/Downloads/uhd-master/fpga/usrp3/top/x300/build-X310_HG/X310.srcs/sources_1/imports/usrp3/top/x300/x300.v":656]

[Synth 8-1031] DMA_STREAM_WIDTH is not declared ["/home/scoe-adm/Downloads/uhd-master/fpga/usrp3/top/x300/build-X310_HG/X310.srcs/sources_1/imports/usrp3/top/x300/x300.v":664]

[Common 17-69] Command failed: Synthesis failed - please see the console or run log file for details

I'm absolutely blocked, any help is highly appreciated.

Kind Regards,

-----------------------------------------
Dipl.-Ing. Arash Jafari 

Phone: +43 650 844 3617
E-mail: arash.jafari.telecom@gmail.com

**Comment by mbr0wn** [comment] 2020-10-06 09:50
Does it work without GUI=1?

**Comment by mbr0wn** [comment] 2020-10-06 09:52
Also note the paths you are printing are for UHD 4, and not for UHD-3.15. Have you tried cloning https://github.com/EttusResearch/fpga and building that for UHD-3.15?

**Comment by arash1366j** [comment] 2020-10-06 12:17
Dear mbr0wn,
Thank you very mush for your response.
without GUI=1(in batch mode), it generates the **.bit** file without any problem!
But in GUI mode the configuration is not correct!
I've tried uhd 3.14 L, uhd 3.15 LTS, uhd master (4). All of them result in the same issue.

Kind Regards

**Comment by jpendlum** [comment] 2020-10-06 17:58
@arash1366j 

Make sure when you save your Vivado project to **not** select the option to copy the source files. I believe that is the cause of your issue.

**Comment by arash1366j** [comment] 2020-10-07 08:50
Dear Jonathon,

Thank you for your response 

The option you are talking about is available in Add sources not in save as (See  attachment), I would be grateful if you can explain in details?

Regards
![Save-as](https://user-images.githubusercontent.com/56346146/95309000-deb75d00-088a-11eb-8b6d-30821aa3726e.PNG)
![Add-sources](https://user-images.githubusercontent.com/56346146/95309053-ef67d300-088a-11eb-916f-1d9721aa2c0e.PNG)

**Comment by mbr0wn** [comment] 2020-10-08 07:08
Since this is resolve; closing.

**Closed by mbr0wn** 2020-10-08 07:08 UTC
