### ISSUE TITLE
Symbol link error while running .exe built on ubuntu

### ISSUE THREAD

**Issue by ananth42** [EttusResearch/uhd#374] opened 2020-09-03 05:48 UTC
I've installed uhd on my centos 7 building it from source. But my projects are w.r.t ubuntu. So I'm trying to run my .exe built on ubuntu on my centos. The code runs fine without UHD. However if I try to run with UHD, I get symbol look up error. I've done ldd and checked, all the libraries required are present. The following is the error I'm getting:

symbol lookup error: ./Radio_USRP: undefined symbol: _ZN3uhd4usrp10multi_usrp9ALL_GAINSB5cxx11E

I tried looking where this symbol is defined, it points to libuhd.so.3.14.0 in ubuntu . But the same, I'm not finding on centos even though I can find libuhd.so.3.14.0. Are some symbols defined specific to OS? Is there a way to work around it? I don't want to build my program on centos.

**Comment by michaelld** [comment] 2020-09-03 13:56
@ananth42 : This is not a bug with UHD, though it is UHD related so please send an email to "support@ettus.com" and we'll try to help you there. I'm closing this issue.

**Closed by michaelld** 2020-09-03 13:56 UTC
