### ISSUE TITLE
'blockdef' test fails in rfnoc-devel branch, build UHD_4.0.0.rfnoc-devel-409-gec9138eb

### ISSUE THREAD

**Issue by stojadin** [EttusResearch/uhd#141] opened 2017-11-03 16:21 UTC
After compiling the rfnoc-devel branch, `make test` returns the following error:

```
98% tests passed, 1 tests failed out of 42

Total Test time (real) =   0.85 sec

The following tests FAILED:
         27 - blockdef_test (Failed)
Errors while running CTest
Makefile:61: recipe for target 'test' failed
make: *** [test] Error 8

```
For more information, `ctest -V -R blockdef` returns the following:

```
UpdateCTestConfiguration  from :/root/uhd/host/build/DartConfiguration.tcl
UpdateCTestConfiguration  from :/root/uhd/host/build/DartConfiguration.tcl
Test project /root/uhd/host/build
Constructing a list of tests
Done constructing a list of tests
Checking test dependency graph...
Checking test dependency graph end
test 27
    Start 27: blockdef_test

27: Test command: /bin/sh "/root/uhd/host/build/tests/blockdef_test_test.sh"
27: Test timeout computed to be: 9.99988e+06
27: Running 4 test cases...
27: 6
27: Testing NullSrcSink => 0000000000000000
27: Testing SchmidlCox => 5CC0000000000000
27: Testing Window => D053000000000000
27: Testing FIR => F112000000000001
27: Testing FIFO => F1F0000000000000
27: Testing FFT => FF70000000000000
27: /root/uhd/host/tests/blockdef_test.cpp(84): fatal error in "test_regs": critical check sregs.size() == 3 failed [6 != 3]
27: 
27: *** 1 failure detected in test suite "Master Test Suite"
1/1 Test #27: blockdef_test ....................***Failed    0.03 sec

0% tests passed, 1 tests failed out of 1

Total Test time (real) =   0.03 sec

The following tests FAILED:
         27 - blockdef_test (Failed)
Errors while running CTest
```

Compiling and testing on both ubuntu 14.04 and 16.04, on clean systems with only the UHD required dependencies installed (the list of which is found [here](https://kb.ettus.com/Building_and_Installing_the_USRP_Open-Source_Toolchain_(UHD_and_GNU_Radio)_on_Linux)), resulted in the same errors.

This happens with `UHDlinux; GNU C++ version 5.4.0 20160609; Boost_105800; UHD_4.0.0.rfnoc-devel-409-gec9138eb` and has not happened to me with earlier builds.

**Comment by michael-west** [comment] 2018-02-16 17:36
@stojadin Thank you for letting us know.  The rfnoc-devel branch is an unstable development branch and these types of errors are expected.  This issue will be addressed before the rfnoc-devel branch gets fully merged into the master branch because any merge into the master branch is only be permitted after a set of regression tests pass and those tests include "make test".  We are closing this issue for now because it will be fixed before the merge into the mainstream code base and because it should not block any development.

**Closed by michael-west** 2018-02-16 17:36 UTC
